name: pets
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  sqflite: ^2.2.2
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^7.0.1
  path_provider: ^2.0.11
  confetti: ^0.7.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

